export const allEmployees = [
  { employeeCode: 'E001', employeeName: 'John Doe', designation: 'Manager', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Active' },
  { employeeCode: 'E002', employeeName: 'Alice Brown', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Archived' },
  { employeeCode: 'E003', employeeName: 'Michael Green', designation: 'Designer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E004', employeeName: 'Sarah White', designation: 'HR', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E005', employeeName: 'Robert Black', designation: 'QA Engineer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Archived' },
  { employeeCode: 'E006', employeeName: 'Laura King', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Active' },
  { employeeCode: 'E007', employeeName: 'Daniel Scott', designation: 'Manager', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E008', employeeName: 'Emma Taylor', designation: 'Designer', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Archived' },
  { employeeCode: 'E009', employeeName: 'James Harris', designation: 'QA Engineer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Active' },
  { employeeCode: 'E010', employeeName: 'Olivia Moore', designation: 'HR', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Archived' },
  { employeeCode: 'E011', employeeName: 'William Clark', designation: 'Developer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E012', employeeName: 'Sophia Lewis', designation: 'Manager', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E013', employeeName: 'Henry Walker', designation: 'Designer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Archived' },
  { employeeCode: 'E014', employeeName: 'Isabella Hall', designation: 'QA Engineer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Active' },
  { employeeCode: 'E015', employeeName: 'Lucas Allen', designation: 'Developer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Archived' },
  { employeeCode: 'E016', employeeName: 'Mia Young', designation: 'Manager', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E017', employeeName: 'Ethan Wright', designation: 'HR', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Active' },
  { employeeCode: 'E018', employeeName: 'Ava Martinez', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Archived' },
  { employeeCode: 'E019', employeeName: 'Mason Hill', designation: 'Designer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E020', employeeName: 'Charlotte Lopez', designation: 'QA Engineer', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E021', employeeName: 'Benjamin Perez', designation: 'Manager', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Archived' },
  { employeeCode: 'E022', employeeName: 'Amelia Gonzalez', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Active' },
  { employeeCode: 'E023', employeeName: 'Elijah Carter', designation: 'Designer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E024', employeeName: 'Harper Mitchell', designation: 'HR', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Archived' },
  { employeeCode: 'E025', employeeName: 'Alexander Roberts', designation: 'QA Engineer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Active' },
  { employeeCode: 'E026', employeeName: 'Evelyn Turner', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Archived' },
  { employeeCode: 'E027', employeeName: 'Sebastian Phillips', designation: 'Manager', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E028', employeeName: 'Abigail Campbell', designation: 'Designer', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E029', employeeName: 'Jack Parker', designation: 'QA Engineer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Archived' },
  { employeeCode: 'E030', employeeName: 'Ella Evans', designation: 'HR', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Active' },
  { employeeCode: 'E031', employeeName: 'Logan Edwards', designation: 'Developer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E032', employeeName: 'Scarlett Collins', designation: 'Manager', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Archived' },
  { employeeCode: 'E033', employeeName: 'Matthew Stewart', designation: 'Designer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Active' },
  { employeeCode: 'E034', employeeName: 'Grace Sanchez', designation: 'QA Engineer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Active' },
  { employeeCode: 'E035', employeeName: 'Joseph Morris', designation: 'Developer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Archived' },
  { employeeCode: 'E036', employeeName: 'Victoria Rogers', designation: 'Manager', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E037', employeeName: 'Samuel Reed', designation: 'HR', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Active' },
  { employeeCode: 'E038', employeeName: 'Chloe Cook', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Archived' },
  { employeeCode: 'E039', employeeName: 'David Morgan', designation: 'Designer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E040', employeeName: 'Zoey Bell', designation: 'QA Engineer', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E041', employeeName: 'Ryan Murphy', designation: 'Manager', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Archived' },
  { employeeCode: 'E042', employeeName: 'Lily Bailey', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Active' },
  { employeeCode: 'E043', employeeName: 'Andrew Rivera', designation: 'Designer', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E044', employeeName: 'Hannah Cooper', designation: 'HR', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Archived' },
  { employeeCode: 'E045', employeeName: 'Nathan Richardson', designation: 'QA Engineer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Active' },
  { employeeCode: 'E046', employeeName: 'Zoe Howard', designation: 'Developer', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Archived' },
  { employeeCode: 'E047', employeeName: 'Hunter Ward', designation: 'Manager', center: 'C3', campus: 'Design', zone: 'East', reportingManager: 'Mary Johnson', status: 'Active' },
  { employeeCode: 'E048', employeeName: 'Layla Torres', designation: 'Designer', center: 'C4', campus: 'Admin', zone: 'West', reportingManager: 'David Lee', status: 'Active' },
  { employeeCode: 'E049', employeeName: 'Aaron Peterson', designation: 'QA Engineer', center: 'C1', campus: 'Main', zone: 'North', reportingManager: 'Jane Smith', status: 'Archived' },
  { employeeCode: 'E050', employeeName: 'Brooklyn Gray', designation: 'HR', center: 'C2', campus: 'Tech', zone: 'South', reportingManager: 'John Doe', status: 'Active' }
];
